name: aureascan_app
description: A new Flutter project for AureaScanAI.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  http_parser: ^4.0.2
  camera: ^0.11.0+1
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  web_socket_channel: ^2.4.0
  image_picker: ^1.0.7
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-Light-BETA.otf
          weight: 300 